### ISSUE TITLE
Bug: Icons do not render in full static mode in RC10

### ISSUE THREAD

**Issue by fayazara** [nuxt-modules/icon#8] opened 2022-09-17 13:03 UTC
I am using this module and when I use it with RC10s full static mode. It does not render the icon, adds the icon name as a string.

![Screenshot2022-09-17 at 18 30 35](https://user-images.githubusercontent.com/15716057/190858142-dcf6977b-26ce-4fb3-a134-7759b1e0be2e.png)

As you can see, it is just using the fallback as the icon name instead of rendering the svg `<span v-else class="icon" :style="{ fontSize: sSize, lineHeight: sSize, width: sSize, height: sSize }">{{ name }}</span>`

CC: @Atinux

**Comment by Atinux** [comment] 2022-09-17 13:25
I believe this will be resolved in RC11. Cc @pi0 @danielroe

**Comment by Atinux** [comment] 2022-09-19 12:18
Tested on Nuxt Edge and works, can you confirm too @fayazara?

**Comment by fayazara** [comment] 2022-09-19 12:23
Is nuxt edge a preview branch? @Atinux  How do I use it?

**Comment by danielroe** [comment] 2022-09-19 12:34
https://v3.nuxtjs.org/guide/going-further/edge-channel/

**Comment by sigliblog** [comment] 2022-09-20 16:17
[vite:vue] Transform failed with 2 errors:
7:09:01 PM: /opt/build/repo/node_modules/nuxt-icon/dist/runtime/Icon.vue:8:0: ERROR: Transforming const to the configured target environment ("ES5") is not supported yet
7:09:01 PM: /opt/build/repo/node_modules/nuxt-icon/dist/runtime/Icon.vue:10:2: ERROR: Transforming const to the configured target environment ("ES5") is not supported yet

can you all advice me tsconfig "compilerOptions" target

**Comment by danielroe** [comment] 2022-09-21 08:37
@sigliblog That seems like a different issue. Would happily look at it; would you mind opening a new issue with a reproduction? 🙏

**Comment by danielroe** [comment] 2022-09-21 08:43
In my testing I can't reproduce this issue with RC11, so I'm closing it for now (but would welcome a new issue as mentioned above).

**Closed by danielroe** 2022-09-21 08:43 UTC
